'use client'
import '../../globals.css'
import { Inter } from 'next/font/google'
import { ApiProvider } from '@reduxjs/toolkit/dist/query/react'
import { api } from './api/ProductSlice/ProductSlice'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <ApiProvider api={api}>
             {children}
          </ApiProvider>
      </body>
    </html>
  )
}
